version: 2.1 

jobs:
  test:
    docker:
      - image: cimg/node:20.11.1 
    steps:
      - checkout
      - run: npm install 
      - run: npm test

workflows:
  build_and_test:
    jobs:
      - test
