version: 2
jobs:
  test:
    docker:
    - image: circleci/node:8.12.0-jessie
    steps:
    - checkout
    - run:
        name: Test
        command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - test:
        requires:
        - build
        filters:
          branches:
            only: master